name: CI + CD

on:
  pull_request:
    branches:
      # run on created PR for every branch
      - '**'
  push:
    branches: [main]
    tags:
      - '**'
  workflow_dispatch:

jobs:
  install-dependencies:
    name: 'Install Node.js dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js dependencies
        run: npm install

  deploy-dev:
    name: 'Build & Deploy @ DEV'
    if: github.event_name == 'pull_request'
    needs: [install-dependencies]
    runs-on: ubuntu-latest

    steps:
      - name: Result
        run: echo "dev pipeline"

  deploy-uat:
    name: 'Build & Deploy @ UAT'
    if: ${{ (github.event.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' ) }}
    needs: [install-dependencies]
    runs-on: ubuntu-latest

    steps:
      - name: Result
        run: echo "uat pipeline"

  deploy-prod:
    name: 'Build & Deploy @ PROD'
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: [install-dependencies]
    runs-on: ubuntu-latest

    steps:
      - name: Result
        run: echo "uat pipeline"
